(function(e){var k=window.AmazonUIPageJS||window.P,l=k._namespace||k.attributeErrors,f=l?l("AmazonHomepageCardAssets",""):k;f.guardFatal?f.guardFatal(e)(f,window):f.execute(function(){e(f,window)})})(function(e,k,l){e.register("gw-video-orchestrator",function(){function f(a,b,g){return 0<a?Math.min(g-a,b-a):0<b?Math.min(b,g):0}function n(a){var b=k.innerHeight||document.documentElement.clientHeight,g=k.innerWidth||document.documentElement.clientWidth;a=a.getBoundingClientRect();var b=f(a.top,a.bottom,
b),g=f(a.left,a.right,g),c=0;if(0<b||0<g)c=b*g;return Math.min(1,Math.max(0,c/((a.bottom-a.top)*(a.right-a.left))))}function p(a,b){return a&&1===a.nodeType&&(a.offsetWidth||a.offsetHeight||a.getClientRects().length)?n(a)<b?!1:!0:!1}function m(a){a=q(a);a!==c&&(c&&c.callback(!1),(c=a)&&"hidden"!==document.visibilityState&&c.callback(!0))}function q(a){if(a)for(var b=d.length;b--;)if(d[b].element===a)return d[b]}function r(a,b){return b.priority-a.priority||n(b.element)-n(a.element)||(a.element.compareDocumentPosition(b.element)&
Node.DOCUMENT_POSITION_FOLLOWING?-1:1)}function t(){if("hidden"in document)return"visibilitychange";for(var a=["webkit","moz","ms"],b=0;b<a.length;b++)if(a[b]+"Hidden"in document)return a[b]+"visibilitychange"}function u(){document.addEventListener(t(),function(){c&&("hidden"===document.visibilityState?c.callback(!1):c.callback(!0))})}var d=[],c,h=function(){c||d.length&&90<=d[0].priority&&m(d[0].element)};e.when("A","ready").execute(function(a){var b=a.capabilities.isAmazonApp;h=function(){if(d.length&&
(!c||!p(c.element,c.minVisiblePercentForLeader||(b?.95:.5))||"visible"!==getComputedStyle(c.element).visibility)){var a=d.filter(function(a){return p(a.element,a.minVisiblePercentForLeader||(b?.95:.5))&&"visible"===getComputedStyle(a.element).visibility});m(0<a.length?a[0].element:l)}};a.on("scroll resize orientationChange",h);a.on("gw:mobile:registerHorizontalScrolling",function(a){a.addEventListener("scroll",h)});e.when("gw-desktop-herotator").execute(function(a){a.addObserver("animation_complete",
h)});u();h()});return{subscribe:function(a,b,c){if(!a||!b)throw Error("Subscribe required a valid element and callback function");c=c||{};b={element:a,callback:e.guardCurrent(b),minVisiblePercentForLeader:c.minVisiblePercentForLeader,priority:c.priority||50};if(q(a))throw Error("element is already subscribed");d.push(b);d.sort(r);h()},unsubscribe:function(a){if(!a)throw Error("unsubscribe requires a valid element");c&&c.element===a&&m();for(var b=d.length;b--;)d[b].element===a&&(d.splice(b,1),h())},
elect:m,subscribeToHorizontal:function(a){e.when("A","ready").execute(function(b){b.trigger("gw:mobile:registerHorizontalScrolling",a)})}}})});
/* ******** */
(function(n){var g=window.AmazonUIPageJS||window.P,q=g._namespace||g.attributeErrors,f=q?q("AmazonGatewayAuiAssets",""):g;f.guardFatal?f.guardFatal(n)(f,window):f.execute(function(){n(f,window)})})(function(n,g,q){n.register("gateway-asset-load",function(){g.uet&&g.uet("cf","gateway-asset-load",{wb:1});g.uex&&g.uex("ld","gateway-asset-load",{wb:1})});n.when("A","atfWidgetComponent","load").execute("ah-inst-img-size",function(f,m){function k(a){if(!a)return null;var b=a.src;a=c(a).data("a-hires");
return b===a?null:b}function h(a){"object"===typeof u.ue&&"function"===typeof u.ue.count&&u.ue&&u.ue.count(a,(u.ue.count(a)||0)+1)}function l(a,b){h("gw-img-size-invoke");c.ajax({type:"HEAD",async:!0,url:a,success:function(c,d,e){c=g.performance.getEntriesByName(a).filter(function(a){return"img"===a.initiatorType});0<c.length&&"decodedBodySize"in c[0]?(h("gw-img-size-success"),f.trigger(b,parseInt(c[0].decodedBodySize,10))):h("gw-img-size-error")},error:function(a,b,c){h("gw-img-size-error")}})}function a(a,
d,e){p[d]={count:a.length,totalSize:0,images:c.unique(a)};0==a.length?e&&b(d,e):c(p[d].images).each(function(a,c){a=d+"_"+a;f.on(a,function(a){isNaN(a)||(--p[d].count,p[d].totalSize+=a,0===p[d].count&&(u.ue&&u.ue.count(d,p[d].totalSize),e&&b(d,e)))});l(c,a)})}function b(a,b){--p[b].slotCount;p[b].totalSize+=p[a].totalSize;0==p[b].slotCount&&u.ue&&u.ue.count(b,p[b].totalSize)}function d(a,b){b=b||a.length;var d=[];c(a.slice(0,b)).each(function(a,b){a=k(b);if(!a)return[];d.push(a)});return d}function e(){return g.performance&&
g.performance.getEntriesByName?!1:(h("gw-img-size-error"),!0)}var c=f.$,u=g,p=[];n.execute("inst-cf-img",function(){if(!e()){h("gw-inst-img");var b=f.$(".gw-critical-content img");(b=0>=b.length?null:k(b[0]))&&a([b],"gw-cf-img-size")}});n.execute("inst-atf-img",function(){if(!e()){h("gw-atf-img");var b=m.getWidgets();b&&(b=b.filter(function(a){return a&&0<a.length}));b!=q&&0!=b.length&&(p["gw-atf-img-size"]={slotCount:b.length,totalSize:0},c.each(b,function(b,e){b="gw-"+e+"-img-size";var h;h=c("#"+
e+".desktop-row.gwi-row");h!=q&&0<h.length?(e="#"+e+" img",h=7):(e="#"+e+" .a-cardui-body img",h=q);e=d(c(e),h);a(e,b,"gw-atf-img-size")}))}})});"use strict";n.when("A").register("dombinder",function(f){function m(a,b){var d=0;b=b.split(".");for(var e=b.length;d<e;d++)a=a&&a[b[d]];return a}function k(a){return h.map(h(a).data("bind").split(","),function(b){b=b.split(":");var d=h.trim(b[0]),e=h.trim(b[1]),c=l[d];if(c)return c.init&&c.init(a,e),function(b){c.update(a,e,b)}})}var h=f.$,l={text:{update:function(a,
b,d){h(a).text(m(d,b)||"")}},html:{update:function(a,b,d){h(a).html(m(d,b)||"")}},href:{update:function(a,b,d){h(a).attr("href",m(d,b)||"")}},trimText:{update:function(a,b,d){a=h(a);d=a.text();if(d.length>b){for(var e=b-4;0<=e&&0<"[.,-/#!$%^\x26*;:{}\x3d-_`~()] ".indexOf(d[e]);)e--;a.text(d.substring(0,0<=e?e+1:b-3)+"...")}}},value:{update:function(a,b,d){h(a).val(m(d,b)||"")}},visible:{update:function(a,b,d){var e=!1;"!"===b.charAt(0)&&(e=!0,b=b.substring(1));b=!!m(d,b);e!==b?h(a).show():h(a).hide()}},
css:{init:function(a,b){a=h(a);var d=a.data("dombcss")||[];d[b]="";a.data("dombcss",d)},update:function(a,b,d){a=h(a);var e=a.data("dombcss"),c=e[b];d=m(d,b);c!==d&&(e[b]=d,c&&a.removeClass(c),d&&a.addClass(d))}},attr:{init:function(a,b){a=h(a);var d=a.data("dombattr")||[];d[b]={};a.data("dombattr",d)},update:function(a,b,d){var e=h(a);a=e.data("dombattr");var c=a[b];d=m(d,b);c!==d&&(a[b]=d,c&&h.each(c,function(a,b){e.removeAttr(a)}),d&&h.each(d,function(a,b){e.attr(a,b)}))}}};return{init:function(a){var b=
{$root:a,bindings:[]};a.find("[data-bind]").each(function(){h.each(k(this),function(a,e){b.bindings.push(e)})});return b},update:function(a,b){h.each(a.bindings,function(a,e){e(b)})}}});"use strict";n.when("jQuery").register("gwAjax",function(f){return function(m,k){function h(a,e,c){"object"===typeof g.ue&&"function"===typeof g.ue.count&&(l(k.errorCounter||"gwAjaxError"),k.id&&l("gwAjaxError:"+k.id));"function"===typeof g.ueLogError&&g.ueLogError({logLevel:"WARN",attribution:"gwAjax-"+(k.id||m),
message:"gwAjax call failed "+(JSON&&JSON.stringify?JSON.stringify({url:m,"params-data":k.params||k.data}):"")});"function"===typeof b&&b(a,e,c)}function l(a){"object"===typeof g.ue&&"function"===typeof g.ue.count&&g.ue.count(a,(g.ue.count(a)||0)+1)}k=f.extend(!0,{},k);var a=k.success,b=k.error;k.success=function(b,e,c){b.error?h(b,e,c):"function"===typeof a&&a(b,e,c)};k.error=h;k.data=k.params?k.params:k.data;l("gwAjaxCall");k.ajaxCounter&&l(k.ajaxCounter);return f.ajax(m,k)}});"use strict";n.when("jQuery",
"gw-hud-punt").execute("gw-hud-sidekick",function(f){f("#gw-hud-grid").css({display:"none"})});"use strict";n.register("gw/card-modal",function(){function f(f,h){if(m)return m(f,h);n.when("__gw-card-modal").execute(function(l){l(f,h)});return{show:function(){}}}var m;n.when("__gw-card-modal").execute(function(f){m=f});return{show:function(k,h){f(k,h).show()},preload:function(k,h){n.when("ready").execute(function(){f(k,h)})}}});n.when("A","a-modal","gw/card-loader").register("__gw-card-modal",function(f,
m,k){var h={},l=f.$;return function(a,b){if(h[a])return h[a];var d=k.decodeToken(a).name,e=l('\x3cspan style\x3d"display: none" /\x3e').appendTo("body");b=l.extend({name:d||"gw-card-popover",closeButton:!0,hideHeader:!0,style:"gw",content:l('\x3cdiv aria-hidden\x3d"true"\x3e\x3c/div\x3e').html(b&&b.loading||'\x3cdiv class\x3d"gw-modal-loading"\x3e\x3ci class\x3d"gw-spinner"\x3e\x3c/i\x3e\x3c/div\x3e')},b);var c=h[a]=m.create(e,b);if("gw"===b.style){var g="#a-popover-"+c.attrs("id"),e=l.map([" .a-popover-inner { overflow: hidden !important; height: 100% !important; min-width: 80px; min-height: 80px; }",
" .a-popover-wrapper { border: none; border-radius: 0; }"],function(a){return g+a}).join(" ");l("head").append("\x3cstyle\x3e"+e+"\x3c/style\x3e");if(b.closeButton)f.on("a:popover:show:"+b.name,function(a){a=l(g);a.find("button.a-button-close").addClass("gw-close-button");a.find(".a-icon.a-icon-close").attr("class","gw-icon gw-icon-close")})}k.request(a).then(function(a){c.update({content:a.html()})});return h[a]}});"use strict";n.when("gw-promise","urlb64decode").register("gw/card-loader",function(f,
m){function k(){try{var a=(new URL(document.location.href)).searchParams.get("cardOverrides");if(a)return"cardOverrides\x3d"+a}catch(b){if(a=document.location.href.match(/[?&](cardOverrides=.*?)([&#]|$)/),null!==a)return a[1]}}var h=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},l={};return{decodeToken:function(a){return JSON.parse(m(a.substring(1)))},request:function(a){function b(a){for(var b=0,c=g.length;b<c;b++)g[b]&&g[b](a)}for(var d=h(a)?a:[a],e=k(),c=
"/homepage.html/ajax/card"+(e?"?"+e:""),e=[],m=[],g=[],x=[],r=0,q=d.length;r<q;r++){var w=d[r];l[w]?e[r]=l[w]:(e[r]=l[w]=f(function(a,b){m[r]=a;g[r]=b}),x[r]={t:w})}0<x.length&&n.when("A").execute(function(a){a.post(c,{chunk:function(b){var c=b[1];c&&(c.ok?m[c.i]&&m[c.i]({render:function(b){a.$(b).html(c.body)},html:function(){return c.body}}):g[c.i]&&g[c.i](c.body))},success:function(a,c,d){b("Not Found")},error:function(a,c,d){b(d)},abort:function(a){b("Aborted")},contentType:"application/json",
paramsFormat:"json",params:x})});return h(a)?e:e[0]}}});g.Promise?n.register("gw-promise",function(){return function(f){return new Promise(f)}}):n.when("jQuery").register("gw-promise",function(f){return function(m){var k=f.Deferred();m(k.resolve,k.reject);return{then:k.then,"catch":function(h){return k.fail(h)}}}});n.register("urlb64decode",function(){if(g.atob){var f={"-":"+",_:"/"};return function(m){return g.atob(m.replace(/[-_]/g,function(k){return f[k]}))}}return function(f){f=f.replace(/\s|=/g,
"");for(var k="",h=0,l=f.length;h<l;h+=4){for(var a=0,b=h,d=24;0<d&&b<l;)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".indexOf(f.charAt(b++))<<(d-=6);k+=String.fromCharCode(a>>>16&255,a>>>8&255,a&255)}return k}});"use strict";n.when("jQuery","dombinder").register("productdb-binding-helper",function(f,m){function k(h,l){return f.isFunction(h)?h(l):l}return function(f,l){function a(a,b){m.update(n,e(b.beforeUpdate,a));a.loading||e(b.load,a)}function b(a){d();g=function(){a(c)};
c.pdb_observe(g)}function d(){c&&g&&(c.pdb_unobserve(g),g=null)}var e=k,c=null,g=null,n=m.init(l);this.setAsin=function(e,l){l=l||{};d();c=f.get(e);a(c,l);c.loading&&b(function(b){a(b,l)});return c};this.clear=function(){d();c={};m.update(n,c)}}});g.P&&n.when("jQuery","afterLoad").register("gw-resource-logger",function(f){return{instrumentResources:function(m){var k;k=!1;if(f.isArray(m)&&!f.isEmptyObject(m)){k=!0;for(var h=0;h<m.length;h++){var l=m[h];if("id"in l&&"regex"in l&&"initiator"in l){if(!("string"===
typeof l.id&&"string"===typeof l.initiator&&l.regex instanceof RegExp)){k=!1;break}}else{k=!1;break}}}h=g.performance&&"function"===typeof g.performance.getEntriesByType&&"undefined"!==typeof g.performance.getEntriesByType("resource")&&"undefined"!==typeof g.ue;if(k&&h){k=Array(m.length);for(h=0;h<k.length;h++)k[h]=!1;for(l=h=0;l<g.performance.getEntriesByType("resource").length&&h<m.length;l++)for(var a=g.performance.getEntriesByType("resource")[l],b=a.name,d=a.initiatorType,e=0;e<m.length;e++)if(!k[e]){var c=
m[e].regex;if(d===m[e].initiator&&c.test(b)){b=m[e].id;d=a.duration;g.ue.count&&(g.ue.count(b+":duration",d),g.ue.count(b+":startTime",a.startTime));g.ue.tag&&g.ue.tag(50>d?b+":cached":b+":notCached");k[e]=!0;h++;break}}}}}});"use strict";n.register("sg-media-builder",function(){return function(f){var g=this,k=f.src,h=[];g.build=function(){var g=h.join("_");return{src:k.replace(/\.([^.]+)$/,"._"+g+"_.$1"),alt:f.alt}};g.autoCrop=function(){h.push("AC");return g};g.scaleX=function(f){h.push("SX"+f);
return g};g.scaleY=function(f){h.push("SY"+f);return g};g.upScaleX=function(f){h.push("UX"+f);return g};g.upScaleY=function(f){h.push("UY"+f);return g};g.scaleXY=function(f,a){return g.upScaleX(f).scaleY(a)}}});"use strict";n.when("jQuery","gwAjax").register("shogunProductDB",function(f,m){function k(a){var b=[];l[a]={loading:!0,pdb_observe:function(a){b.push(a)},pdb_unobserve:function(a){b=f.grep(b,function(b){return b!==a})},_trigger:function(){f.each(b,function(){this.call(l[a])})}};return l[a]}
function h(a,b){this.ajaxUrl=a;this.experienceStr=b;this._add=function(a){a.p&&f.each(a.p,function(a,b){b.asin&&(a=l[b.asin]||k(b.asin),f.extend(a,b,{loading:!1,error:!1}),a._trigger(b))})};this.addSims=function(a,b){if(b){var c=l[a]||k(a);f.extend(c,{sims:b});c._trigger(a)}};this._ajax=function(d,e,c){c=c||{};d=f.extend(!0,{},a,{params:{sa:d,oe:b}},c);g.ue_id&&(d.params.rrid=g.ue_id);return m(d.url,{method:d.method,params:d.params,success:e.success,error:e.error,id:"gw-jslibs-"+e.id})};this.get=
function(a){return a in l?l[a]:k(a)}}var l={};return function(a,b){return new h(a,b)}});"use strict";n.when("A","jQuery","af").register("layout-tags",function(f,m){function k(){var f={twoColumn:[0,919],threeColumn:[920,1239],fourColumn:[1240,1539],fiveColumn:[1540,1E4],twoColumnRevised:[0,979],threeColumnRevised:[980,1299],fourColumnRevised:[1300,1619],fiveColumnRevised:[1620,1E4]},a=m("html").width(),b=[],d;for(d in f){var e=f[d],c=e[1];a>=e[0]&&a<=c&&b.push(d)}return b}var h=function(){var h=[],
h=h.concat(k()),a;a=f.$("\x3cdiv\x3e\x3c/div\x3e")[0];a=""===a.style.flex||""===a.style.webkitFlex||""===a.style.msFlex||""===a.style.MozBoxFlex||""===a.style.webkitBoxFlex?!0:!1;a&&h.push("flexLayout");""===f.$("\x3cdiv\x3e\x3c/div\x3e")[0].style.grid&&h.push("cssGridLayout");return h}();(function(f){if(g.ue&&ue.tag)for(var a=0;a<f.length;a++)ue.tag(f[a])})(h);return{layoutTags:h}});"use strict";n.when("jQuery","p-detect").register("component-feed-carousel",function(f,m){var k=f.extend(!0,{},m);
f.each({pointerPrefix:function(){return"onmspointerup"in document||"onpointerup"in document?"onpointerup"in document?"pointer":"MSPointer":!1},actionMode:function(){var a=k.capabilities.pointerPrefix;return a?a:k.capabilities.touch?"touch":"mouse"}},function(a,b){k.capabilities[a]=b()});var h={};f.each({start:{mouse:"down",touch:"start",pointer:"down",MSPointer:"Down"},end:{mouse:"up",touch:"end",pointer:"up",MSPointer:"Up"}},function(a,b){var d=k.capabilities.actionMode,e="string"===typeof b?b:b[d];
h[a]=e?d+e:b.mouse===q?"":"mouse"+b.mouse});k.action=h;var l=function(a,b,d,e){this.init(a,b,d,e)};l.prototype={init:function(a,b,d,e){var c=this;f("html").hasClass("a-touch")&&a.addClass("feed-carousel-touch");c.config=e||{};c.adjustMarginOnChange=!1!==c.config.adjustMarginOnChange;c.defaultCssRightMargin=null;c.minItems=b||10;c.imgClass=".product-image";c.$carousel=a;c.cfMinItems=d||6;c.cfFired=!1;c.shovelerReadyFired=!1;c.slotId=c.getSlotId();c.touch=c.$carousel.hasClass("feed-carousel-touch");
c.ajaxSource=c.$carousel.parent().hasClass("ajaxSource");c.$shelf=c.$carousel.find(".feed-carousel-shelf");c.$viewport=c.$carousel.find(".feed-carousel-viewport");c.$spinner=c.$carousel.find(".spinner");c.$left=f(".feed-carousel-control.feed-left",a);c.$right=f(".feed-carousel-control.feed-right",a);c.$buttons=f(".feed-carousel-control",a);c.$thumb=f(".feed-scrollbar-thumb",a);c.shelfLeft=-1*parseInt(c.$shelf.css("left"),10);c.calcWidth=f("html").hasClass("a-lt-ie9");c.noOpacity=f("html").hasClass("a-lt-ie9");
c.uniqueId=c.getUniqueId();c.$left.attr("aria-hidden",!0);c.$right.attr("aria-hidden",!0);c.bindEvents();c.$carousel.data("Carousel",c);c.$carousel.trigger("change");c.token=!1;c.lock=function(){c.token=!0};c.unlock=function(){c.token=!1};c.locked=function(){return c.token};n.when("gw-first-carousel").execute(function(){c.first=c.$carousel.hasClass("first-carousel");c.shouldControlsOn()?c.showControls():c.hideControls()});c.uniqueId&&n.when(c.uniqueId).execute(function(a){c.appendCards(a.cards);if(a.cards&&
c.slotId&&"object"===typeof g.ue&&"function"===typeof g.ue.count){var b="gw-"+c.slotId.toString()+"-lazy-cards",d="gw-"+c.slotId.toString()+"-lazy";g.ue.count(b,(g.ue.count(b)||0)+a.cards.length);g.ue.count(d,(g.ue.count(d)||0)+1)}n.register(c.uniqueId+"-lazy-cards-loaded");g.GWI.register(c.uniqueId+"-lazy-cards-loaded")})},getUniqueId:function(){if(this.$viewport){var a=this.$viewport.closest(".shogun-widget");return 0<a.length?f(a[0]).attr("id"):null}},getSlotId:function(){var a=this.$carousel.closest(".gw-widget-instrument");
return 0<a.length?f(a[0]).attr("id"):null},getMouseDirection:function(){return k.capabilities.rtl?-1:1},bindEvents:function(){function a(a){return k.capabilities.pointerPrefix&&-1<f.inArray(a.originalEvent.pointerType,[2,"touch"])||"touch"===k.capabilities.actionMode}var b=this,d=f("body");b.$buttons.ready(function(a){b.shovelerReadyFired||(b.slotId&&(a=b.slotId.toString()+"-active",g.GWI&&g.GWI.recordLatency(a),g.GWI&&g.GWI.register(a)),b.shovelerReadyFired=!0)});b.$carousel.change(function(a){b.updateItems();
b.updateSpinner();b.updateShelf();b.updateControls();null===b.defaultCssRightMargin&&b.$shelf.children("li").first()&&(a=parseInt(b.$shelf.children("li").first().css("margin-right"),10),b.defaultCssRightMargin=isNaN(a)?10:a);b.adjustMarginOnChange&&b.adjustCardMargin()});b.$left.click(function(a){a.preventDefault();b.changePage(-1);b.slotId&&b.logCounter("gw-"+b.slotId.toString()+"-left")});b.$right.click(function(a){a.preventDefault();b.changePage(1);b.slotId&&b.logCounter("gw-"+b.slotId.toString()+
"-right")});b.bindImageLoadEvents(b.$shelf);var e;f(g).resize(function(){clearTimeout(e);e=setTimeout(function(){var a=b.getDimensions();b.moveShelf(Math.max(Math.min(a.shelfLeft,a.maxLeft),0));b.updateShelf()},100)});b.$thumb.mousedown(function(a){var e=a.clientX;1===a.which&&(a.preventDefault(),b.$carousel.addClass("scrolling"),d.bind("mousemove.feed-carousel",function(a){var c=b.getDimensions(),d=b.getMouseDirection()*(a.clientX-e),c=Math.max(Math.min(c.shelfLeft+1/c.pageRatio*d,c.maxLeft),0);
e=a.clientX;b.moveShelf(c)}),f(document).bind("selectstart.feed-carousel",function(){return!1}))});d.add(g).mouseup(function(a){b.$carousel.removeClass("scrolling");b.$carousel.hasClass("hovering")||b.hideControls();d.unbind("mousemove.feed-carousel");f(document).unbind("selectstart.feed-carousel")});b.$carousel.hover(function(){b.$carousel.addClass("hovering");clearTimeout(b.hoverTimer);b.hoverTimer=setTimeout(function(){b.$carousel.hasClass("hovering")&&!b.$carousel.hasClass("touching")?b.showControls():
b.$carousel.removeClass("touching")},300)},function(){b.$carousel.removeClass("hovering touching");clearTimeout(b.hoverTimer);b.$carousel.hasClass("scrolling")||(b.hoverTimer=setTimeout(function(){b.$carousel.hasClass("hovering")||b.hideControls()},600))});b.$carousel.bind(k.action.start,function(c){a(c)&&(b.$carousel.addClass("touching"),clearTimeout(b.touchTimer),b.touchTimer=setTimeout(function(){b.$carousel.removeClass("touching")},5E3))});b.$carousel.bind(k.action.end,function(c){a(c)&&(b.$carousel.removeClass("touching"),
clearTimeout(b.touchTimer),clearTimeout(b.hoverTimer))});b.$viewport.scroll(function(){b.shelfLeft=b.$viewport.scrollLeft();b.updateControls()})},bindImageLoadEvents:function(a){var b=this;f(b.imgClass,a).one("load",function(){b.$carousel.trigger("change")})},getDimensions:function(){var a=this.$shelf.width(),b=this.shelfLeft,d=this.$carousel.width();return{pageWidth:d,shelfWidth:a,shelfLeft:b,pageRatio:d/a,leftRatio:b/a,maxLeft:a-d}},updateItems:function(){var a=this,b=a.$shelf.find(".feed-carousel-card");
f("#"+a.uniqueId);b.each(function(b,e){e=f(e);if("none"!==e.css("display")&&!a.config.visibleBeforeLoad)return!0;e.attr("aria-posinset",b+1);e.attr("aria-hidden",!1);e.attr("role","listitem");return 0>=e.find(a.imgClass).filter(function(){return!this.complete}).length?(e.css("display","inline-block"),b+1>=a.cfMinItems&&!a.cfFired&&(a.slotId&&(b=a.slotId.toString()+"-visible",g.GWI&&g.GWI.recordLatency(b),g.GWI&&g.GWI.register(b)),a.cfFired=!0),!0):!1});b.attr("aria-setsize",b.size());a.$items=b.filter(function(){return"none"!==
f(this).css("display")})},updateShelf:function(){var a=0;this.calcWidth&&(this.$shelf.children().each(function(){a+=f(this).outerWidth(!0)}),this.$shelf.width(a));this.touch&&this.$carousel.not(".fresh-shoveler-tablet-app .feed-carousel").height(this.$shelf.outerHeight(!0))},updateSpinner:function(){this.size()<this.minItems&&this.ajaxSource?this.$spinner.show():(this.size()<this.minItems&&"object"===typeof g.ue&&"function"===typeof g.ue.count&&g.ue.count("shovelerNotEnoughItem",(g.ue.count("shovelerNotEnoughItem")||
0)+1),this.$spinner.hide())},updateControls:function(){this.updateArrows();this.updateScrollThumb()},shouldControlsOn:function(){return this.first&&!this.touch},showControls:function(a){this.$thumb.add(this.$buttons).stop(!0,!0).fadeIn({duration:300,complete:a,queue:!1})},hideControls:function(a){var b=this.$thumb;this.shouldControlsOn()||(b=b.add(this.$buttons));b.stop(!0,!0).fadeOut({duration:300,complete:a,queue:!1})},appendCards:function(a){this.$shelf.append(a);this.bindImageLoadEvents(a);this.$carousel.trigger("change")},
updateArrows:function(){var a=this,b=a.getDimensions();f.each([{$e:a.$left,enabled:0<b.shelfLeft},{$e:a.$right,enabled:b.shelfLeft<b.maxLeft}],function(b,e){b=e.$e;e.enabled?b.removeClass("feed-control-disabled"):b.addClass("feed-control-disabled");a.noOpacity&&(e.enabled?b.css("opacity","1"):b.css("opacity","0.5"))})},updateScrollThumb:function(){var a=this.getDimensions(),b=a.leftRatio*a.pageWidth;this.$thumb.width(Math.min(a.pageRatio*a.pageWidth,a.pageWidth)).each(function(){f(this).animate({left:b},
0)})},logCounter:function(a){"object"===typeof g.ue&&"function"===typeof g.ue.count&&(g.ue.count(a,(g.ue.count(a)||0)+1),g.ue.count("gw-shoveler-click",1))},changePage:function(a){var b=this.getDimensions(),d=this.alignWithItem(b.shelfLeft+a*b.pageWidth),d=Math.min(0>a?d.right:d.left,b.maxLeft);this.locked()||(this.lock(),b.shelfLeft===d?(this.bounce(this.$shelf,-30*a),this.bounce(this.$thumb,6*a)):this.moveShelf(d,400))},moveShelf:function(a,b){function d(){e.updateArrows();e.unlock()}var e=this;
b=b||0;e.shelfLeft=a;if(e.touch)e.$viewport.animate({scrollLeft:a},b,"swing",d);else{var c=e.getDimensions(),c=a/c.shelfWidth*c.pageWidth;e.$shelf.animate({left:-a},b,"swing",d);e.$thumb.animate({left:c},b,"swing",function(){e.updateScrollThumb();e.unlock()})}},getItems:function(){return this.$items},size:function(){return this.getItems().length},alignWithItem:function(a){if(0>a)return{left:0,right:0};var b=this,d=b.getItems(),e=d.map(function(){var c=b.cardPosition(f(this));if(a>=c.left&&a<=c.right)return c}).get(0);
return e?e:b.cardPosition(d.last())},cardPosition:function(a){var b=(a.position()||{left:0,right:0}).left;a=b+a.outerWidth(!0);return{left:b,right:a}},bounce:function(a,b){function d(a){var b={};b[e.touch?"left":"marginLeft"]=a;return b}var e=this;a.each(function(){var a=f(this);a.animate(d(b),400,"swing",function(){a.animate(d(0),100,"swing",e.unlock)})})},setCardMargin:function(a){this.$shelf.children("li").first()&&this.$shelf.children("li").first().css("margin-right")!==a+"px"&&(this.$shelf.children("li").css("margin-right",
a+"px"),this.updateShelf())},adjustCardMargin:function(a){a=a===q||null===a?this.defaultCssRightMargin:a;this.setCardMargin(a);var b=this.getDimensions(),b=0>b.maxLeft?Math.ceil(-b.maxLeft/this.size()):a;this.setCardMargin(b<a?a:b)}};return{createCarousel:function(a,b,d,e){f(a).each(function(a,h){a=f(h);new l(a,b,d,e)})}}});"use strict";n.when("jQuery","SafeP").execute("shoveler-lazy-non-visible-images",function(f,m){function k(a){"object"===typeof l.ue&&"function"===typeof l.ue.count&&l.ue.count(a,
(l.ue.count(a)||0)+1)}function h(){l.GWData&&f.each(l.GWData,function(a,b){if(a&&b&&b.data&&!b.loaded){b.loaded=!0;k("gw-lazy-load-all");var d=[];f.each(b.data,function(a,b){f.each(f(b),function(a,b){d.push(b)})});d&&0<d.length&&k("gw-lazy-load-non-empty");m&&m.register(a,function(){return{cards:d}})}})}var l=g;n.when("x1").execute(h);n.when("ready").execute(h);n.when("load").execute(h)});"use strict";n.register("SafeP",function(){var f={};return{register:function(g,k){"string"===typeof g&&"function"===
typeof k&&(f[g]||(f[g]=function(h,g){n.register(h,g);f[h]=function(){}}),f[g]&&f[g](g,k))}}});"use strict";n.when("A").register("gw-count-down",function(f){return function(g,k,h,l,a){function b(a){a=a||{};return{update:a.update||y.noop,count:a.count||y.noop,transition:a.transition||y.noop}}function d(){return b({update:function(){if(l&&l.dealState){var b=l.dealState.toUpperCase();t="AVAILABLE"===b&&86400<h/1E3?e(""):-1<b.indexOf("WAITLIST")?e(a.on_waitlist):"SOLDOUT"===b?e(a.sold_out,E):0<k?c():0<
h?n():e(a.has_ended,B)}t.update();t.count()}})}function e(a,c){return b({update:function(){r(a);f.trigger(c)}})}function c(){A=a.starts_in;return b({update:function(){f.trigger(F);r(v)},transition:function(){t=e(a.started,G);t.update()},count:function(){z=f.interval(function(){k=C-Date.now();p(k,a.starts_in_timer)},1E3)}})}function n(){A=a.ends_in;return b({update:function(){r(v)},transition:function(){t=e(a.has_ended,B);t.update()},count:function(){z=f.interval(function(){h=D-Date.now();p(h,a.ends_in_timer)},
1E3)}})}function p(a,b){var c,d,e;c=Math.floor(a/36E5);d=Math.floor(a/1E3/60%60);e=Math.floor(a/1E3%60);var f=v,g;g=A+" "+q(c)+q(d,!0,!0)+q(e,!1,!0);f.timerString=g;f=v;b=b?b.replace("_hours_",c).replace("_minutes_",d).replace("_seconds_",e):"";f.readoutString=b;r(v);0>=a&&(clearInterval(z),t.transition())}function q(a,b,c){var d="";if(0<a||c)d=("0"+a).slice(-2);if(!c&&0<a||b)d+=":";return d}function r(a){a.readoutString?v=a:(v.readoutString=a,v.timerString=a);f.trigger(H,v)}if(a&&a.starts_in&&a.ends_in&&
a.has_ended&&a.sold_out&&a.on_waitlist&&a.started&&a.starts_in_timer&&a.ends_in_timer){k=parseInt(k,10);h=parseInt(h,10);l=JSON.parse(l);var y=f.$,w=Date.now(),C=w+k,D=w+h,z,A="",v={timerString:"",readoutString:""},B=g+"ended",G=g+"started",H=g+"updateTimer",F=g+"countingDown",E=g+"soldOut",t=d();t.update();f.on(g,function(){t.update()})}}})});
/* ******** */
